### ISSUE TITLE
writing maturity stat

### ISSUE THREAD

**Issue by Zeks** [Zeks/flipper#14]
Idea for the future. ESRB is trash, there needs to be a writing style maturity rating

**Comment by wokste** [comment]
As far as I know there are several age rating systems. Here a few ideas:

- Word length: `age = c1 + c2 * log(average word length) + c3 * log(average number of words per sentence)` where you need to find the values of the constants. I believe this is actually used by publishers as part of their age classification. A more complex system might send the average word length and average number of words in a neural network but a simple one may be adequate.
- Obscure words. This might be combined with the first method, you can check how many words are common. There are lists of the 1000 most common words. The percentage words in this list may indicate difficulty as well.
- Good writing often repeats the same concept in the same sentence as the next. I don't know how sentence correlation can be automated, but it is at least worth thinking about, I guess.

That said, the maturity stat on fanfiction.net is often used to inform about mature themes. This will not be captured in the above formula's.

You can
