### ISSUE TITLE
SQL injection is a thing

### ISSUE THREAD

**Issue by Zeks** [Zeks/flipper#21]
make sure I am at least semi protected before releasing

**Comment by wokste** [comment]
I would advice prepared statements. This is **the** standard against SQL injections and may make your statements run faster as well. (if you cache your prepared statements, which is not too difficult to do).

**Comment by Zeks** [comment]
yeah, probably something along these lines, wasn't a problem for standalone flipper bc you'd have to be a moron to wipe your own DB XD 

But for server it really is going to become necessary

**Comment by Zeks** [comment]
everything dangerous is now a bind param
