### ISSUE TITLE
A discord bot based on flipper

### ISSUE THREAD

**Issue by Zeks** [Zeks/flipper#33]
I think I can make one.
Will read user fav url and output fics in individual posts
Tracking should be done by emoji, then users will be able to rotate and clean up the list the same way they can now even if they wont be able to filter.

**Comment by Zeks** [comment]
In progress.

**Comment by Zeks** [comment]
delayed becaue the bot I was using seems to be problematic.
burned out a bit debugging all the damn errors

**Comment by tn5421** [comment]
Will we be able to import existing UserDB.sqlite databases, or is that feature planned for a post-release patch?

**Comment by Zeks** [comment]
Currently the whole discord branch is on hold because I got pissed at the base bot being broken af.
(though I was using the dev branch instead of master so it's my own problem)

Anyway, there will be no list importing until(unless)  I switch to postgres because currently the whole list is being kept on user side
