### ISSUE TITLE
Exclude fics from own profile

### ISSUE THREAD

**Issue by dutchmega** [Zeks/flipper#65]
When I use the option "Use FFN profile" to generate a list, I would like to automatically exclude fics that are already in my profile.
Manually tagging every fic is a bit unneeded.

**Comment by Zeks** [comment]
"Assign Liked to fics" is there for that exact reason

**Comment by Zeks** [comment]
I am renaming this feature and making it more tighly integrated into recs algorithm.
Hopefully this addresses the issue better
